// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnHLKTg2gjPn5FbxngbLkHBcAD5xXgX3o',
    appId: '1:444244505043:web:532dfd633b65e95ff03f26',
    messagingSenderId: '444244505043',
    projectId: 'internproject-b43f9',
    authDomain: 'internproject-b43f9.firebaseapp.com',
    storageBucket: 'internproject-b43f9.firebasestorage.app',
    measurementId: 'G-8LDG1FS6BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDisTumTaSLexfnWJ2rCLqX1P-J_-53es',
    appId: '1:444244505043:android:1e5729d0562844e3f03f26',
    messagingSenderId: '444244505043',
    projectId: 'internproject-b43f9',
    storageBucket: 'internproject-b43f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdvkaaqb0OqATwlzrh58t8FOvcshyrYcU',
    appId: '1:444244505043:ios:36e54b419516d61ff03f26',
    messagingSenderId: '444244505043',
    projectId: 'internproject-b43f9',
    storageBucket: 'internproject-b43f9.firebasestorage.app',
    iosBundleId: 'com.example.interassignment1',
  );
}
